outputs.tf
This was always producing an error, but prior to Terraform 0.11 these errors were suppressed and shown only in the logs.
Now that Terraform 0.11 shows errors in outputs, they must all be valid in order to use this module.
=> Fix incorrect subnet_id output expression

outputs.tf
So we could access to tags like: 
```
"${lookup(module.ec2.tags[count.index], "Name")}"
```
=> Add tags to output variables

README.md
A small fix to the usage section in the readme file.
`subnet_id` is missing
=> Add missing variable to the usage example

main.tf
- Removes `vpc_security_group_ids` argument from `ignore_changes` lifecycle parameter
`vpc_security_group_ids` was added to `ignore_changes` lifecycle due to #10 and several known issues in Terraform AWS provider related to arguments of aws_instance (https://github.com/terraform-providers/terraform-provider-aws/issues/2036). 
The corresponding issue has been fixed in Terraform AWS provider [v1.9.0](https://github.com/terraform-providers/terraform-provider-aws/releases/tag/v1.9.0) (see https://github.com/terraform-providers/terraform-provider-aws/pull/2338).
=> Stop ignoring changes in vpc_security_group_ids

main.tf
Hello, Anton
I modified the name tag merge to prevent adding suffix in case of only 1 instance is deployed, it may be usefull for non cluster deployement.
Thks
Regards
=> Modify tag name management to add -%d suffixe only if instance_count > 1

.pre-commit-config.yaml, README.md, examples/basic/README.md, examples/basic/outputs.tf, main.tf, outputs.tf, variables.tf
=> Added support for CPU credits

examples/basic/README.md, examples/basic/main.tf, examples/basic/outputs.tf, main.tf, outputs.tf
Thanks @suizman for reporting the bug!
=> Fixed t2-unlimited bug (related issue #35)

main.tf
This narrows the match for things considered to be t2 instances to only
those types that start with "t2.". Previously there was a class of
(invalid) instance types, such as "2b.something" or "t5.something" that
would cause an error on boolean parsing by matching one regex and not
the other.
This uses conditional logic to identify the non-t2 case, since I don't have a good method for implementing the inverse regular expression without negative lookahead assertions, which re2 doesn't support.
=> Narrow t2 selection criteria.

main.tf
Any change in the ebs block device currently triggers re-creation of
this resource which I assume is not intended. In turn any attached
block device will also be re-created because the instance is re-created
creating a loop of re-created resources for each time terraform is
applied.
Workaround by ignoring these changes as suggested in:
https://github.com/terraform-providers/terraform-provider-aws/issues/1297#issuecomment-319359965
=> Ignore changes in the ebs_block_device

README.md, main.tf, variables.tf
#54 Adding the ability to specify either 'subnet_id' or 'subnet_ids' (or both).
=> Allow multiple subnet ids

main.tf
Fix to bug which was introduced in https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/pull/70
Signed-off-by: Denis Iskandarov <d.iskandarov@gmail.com>
=> fix call to local.instance_name

main.tf
Fixes
```
❯ tf plan
Error: local instance_name: count variables are only valid within resources
```
Signed-off-by: Denis Iskandarov <d.iskandarov@gmail.com>
=> fix count variables are only valid within resources

outputs.tf
**Description**
https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/issues/75
The network_interface_id attribute is being removed, switch your attribute references to the primary_network_interface_id attribute instead.
Reference:
https://www.terraform.io/docs/providers/aws/guides/version-2-upgrade.html#resource-aws_instance
https://www.terraform.io/docs/providers/aws/guides/version-2-upgrade.html#network_interface_id-attribute-removal
@antonbabenko @den-is
=> network_interface_id Attribute Removal

examples/basic/main.tf
Field `owners` is required for `aws_ami`, otherwise it fails.
=> Add missing required field

examples/volume-attachment/main.tf, examples/volume-attachment/outputs.tf, examples/volume-attachment/variables.tf
I have to remote the output "instance_id" because I do not know how to iterate from variables created from modules
Related with #49
=> Make number of instances created configurable, defaulting to 1

README.md
By using example code you install outdated module version which does not work anymore.
=> Update module to the current version

README.md, main.tf, outputs.tf
According to issue #79, I add `volume_tags` in output.tf.
Additionally, I add a same naming policy on `volume_tags`. 
I think Issue #60 should be solved by some other effective ways so I don't use the workaround in [here](https://github.com/terraform-providers/terraform-provider-aws/issues/770#issuecomment-348564510). Maybe we can have further discussion.
=> Add volume tags naming and output

README.md, examples/basic/README.md, examples/basic/main.tf, examples/basic/outputs.tf, outputs.tf
=> Added placement groups

examples/basic/main.tf, main.tf, variables.tf
=> Added support for the list of private_ips

main.tf
Since version [v2.7.0](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/releases/v2.7.0) root and EBS volumes support all arguments (including encryption) we don't need to ignore changes in those arguments.
=> Track all changes (remove ignore_changes lifecycle)

.pre-commit-config.yaml, outputs.tf
The outputs are all wrapped in what I think are unneeded functions. I think this is left over from when the resource was split into two.  These function cause problems with external drive attachments and `null_resource` provisioning steps when you adjust the instance count.
I removed the functions what were wrapping the output variables. 
More details are explained in this issue.  
#134
#122
#116
I think only `compact` function is the root cause of the issue but the other functions do not seem to have much benefit anymore.  Please correct me if I'm wrong.
=> Update output.tf to remove unneeded function wrappers

README.md, examples/basic/main.tf, main.tf, variables.tf
=> Added support for user_data_base64

README.md, outputs.tf
I have added "instance count" as output. This can be useful in scenarios like for example planning the amount of route 53 records to create by using it in combination of the rest of outputs of the module. At the moment, all the rest of the outputs cannot be used as "count" value in any other place because Terraform cannot predict how many instances will be created.
=> Instance count as output

main.tf
The check to establish if an instance type belongs to the t family doesn't work for the new t3a type, so I updated the regexp.
=> Updated t instance type check to include t3a type

main.tf
The check to establish if an instance type belongs to the t family doesn't work for the new t3a type, so I updated the regexp.
=> T3a instance

.pre-commit-config.yaml, CHANGELOG.md, README.md, examples/basic/README.md, examples/basic/main.tf, examples/basic/outputs.tf, examples/basic/versions.tf, examples/volume-attachment/README.md, examples/volume-attachment/main.tf, examples/volume-attachment/variables.tf, examples/volume-attachment/versions.tf, main.tf, outputs.tf, variables.tf, versions.tf
Adding support for the `metadata_options` argument of the `aws_instance` resource
#191
=> feat: Add support for "metadata_options" argument

.gitignore, .pre-commit-config.yaml, README.md, examples/basic/README.md, examples/volume-attachment/README.md
- update documentation based on latest `terraform-docs` which includes module and resource sections
- `.gitignore` updated using GitHub provided default standard + 0.14 lockfile ignore
- these are two new sections provided by [`terraform-docs` now](https://github.com/terraform-docs/terraform-docs/releases/tag/v0.11.0)
No
N/A
=> chore: update documentation based on latest `terraform-docs` which includes module and resource sections

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, README.md, examples/basic/README.md, examples/volume-attachment/README.md
- update documentation and pin `terraform_docs` version to avoid future changes
- pin version to avoid unnecessary updates when a PR coincides with a version update for `terraform_docs`
- no
- documentation change only - ci/cd should pass checks
=> chore: update documentation and pin `terraform_docs` version to avoid future changes

README.md, main.tf, versions.tf
Adding tag support to root block device
Actually, all of these parameters are supported for root_block_device block : volume_size, volume_type, iops, .. except tags.
I would suggest to add tags.
=> feat: add tags support to root block device

README.md, examples/basic/main.tf, main.tf, variables.tf
=> fix: root_block_device tags conflicts

README.md, outputs.tf
Added an output for the `ipv6_addresses` of the AWS instances, similar to both `public_ip` and `private_ip`.
Motivation is the same as #241 . In particular, relying on `aws_instance` data source overly complicates working with IPv6 if using `count` or `for_each` in the module, having to split apply into 2 steps: one targeted for this module's instances, another one for the rest of the stuff, as you can't use a dynamic `for_each` in a data source:
```
╷
│ Error: Invalid for_each argument
│
│   on main.tf line 96, in data "aws_instance" "applied_ec2":
│   96:   for_each    = toset(module.ec2[*].id)
│     ├────────────────
│     │ module.ec2 is tuple with 1 element
│
│ The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how …
```
=> feat: Add instance IPv6 addresses to the outputs

README.md, examples/complete/README.md, examples/complete/main.tf, examples/complete/versions.tf, examples/volume-attachment/README.md, examples/volume-attachment/versions.tf, main.tf, versions.tf
- add `instance_metadata_tags` attribute and bump AWS provider to support
- AWS now allows users to attach/query tags via the metadata endpoint service
- No
- `complete` example
=> feat: Add `instance_metadata_tags` attribute and bump AWS provider to support

README.md, examples/complete/main.tf, main.tf, variables.tf, versions.tf, wrappers/main.tf
Added disable_api_stop action attribute to the ec2 instance resource - Supported in latest TF Provider release [4.20.0](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#4200-june-23-2022)
To prevent your instance from being accidentally stopped, you can enable stop protection for the instance. 
No
=> feat: Add support for `disable_api_stop` attribute

examples/complete/README.md, examples/complete/main.tf, main.tf
When trying to call the module with the specification of a Capacity Reservation ID, the module ends up with the following error:
╷
│ Error: Invalid function argument
│
│ on .terraform/modules/terraform-aws-ec2-instance/main.tf line 45, in resource "aws_instance" "this":
│ 45: capacity_reservation_id = lookup(capacity_reservation_target.value, "capacity_reservation_id", null)
│ ├────────────────
│ │ capacity_reservation_target.value is "cr-xxxxxxxx"
│
│ Invalid value for "inputMap" parameter: lookup() requires a map as the
│ first argument.
╵
As per line 45 analysis, it looks like the bug is in the following statement:
capacity_reservation_id = lookup(capacity_reservation_target, "capacity_reservation_id", null)
it should rather be as follows:
capacity_reservation_id = …
=> fix: Assignment of the Capacity Reservation id to an instance

README.md, variables.tf, wrappers/main.tf
The default value for the capacity_reservation_specification is now updated from null to {}
This behaviour better aligns with the general use of the module. 
None
=> fix: The capacity_reservation_specification default value is updated from null to {}

.pre-commit-config.yaml, examples/complete/main.tf, main.tf
- Correct capacity reservation target to work without needing to set an open capacity reservation
- There are two `capacity_reservation_specification` definitions - one in the instance resource and one in the spot request resource. In the original PR only one of the definition was updated correctly to match the default value type of `{}`. This is now synchronized across the two resources
- Ref #285
- Closes #286
- Closes #287
- No
=> fix: Correct capacity reservation target

.pre-commit-config.yaml, README.md, examples/complete/README.md, examples/complete/main.tf, examples/complete/outputs.tf, main.tf, outputs.tf, variables.tf, wrappers/README.md, wrappers/main.tf
- Add support for creating IAM role/instance profile with policies
- Add support for providing AMI vis SSM parameter like Amazon AMIs
- Instance profiles are the preferred means of providing permissions to instances via IAM roles for things like SSM remote access; this streamlines that experience for users
- Amazon is moving to distributing the recommended AMI IDs via SSM Parameters and now this module supports providing just the parameter name in order to pull the appropriate AMI
- Both of these changes together make it quite simple and easy to quickly create a secure "bastion" instance using SSM session manager (instead of SSH/PEM keys)
- No
=> feat: Add support for creating IAM role/instance profile with policies

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, README.md, examples/complete/main.tf, main.tf, variables.tf, wrappers/main.tf
Adding `auto_recovery` option to toggle between `default` and `disabled`. This argument is computed if not configured. 
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-recover.html 
- Resolves #310
No.
=> feat: Add support for `maintenance_options`

README.md, main.tf, outputs.tf
When running `terraform plan` - the `ami` is hidden and marked as sensitive. This happens whether or not an AMI Id is provided or `ami_ssm_parameter` is used. This is because `aws_ssm_parameter`value is by default a sensitive value.
Example:
```
+ resource "aws_instance" "this" {
+ ami                                  = (sensitive value)
+ arn                                  = (known after apply)
+ associate_public_ip_address          = true
+ availability_zone                    = (known after apply)
+ cpu_core_count                       = (known after apply)
+ cpu_threads_per_core                 = (known after apply)
+ disable_api_stop                     = (known after apply)
+ disable_api_termination              = (known after apply)
+ ebs_optimized                        = (known …
```
=> fix: Marked AMI id as nonsensitive

README.md, examples/complete/main.tf, main.tf, variables.tf
Added `tags` to the `ebs_block_device` dynamic block.
The change is not required, however it enables users to add unique tags per block device as opposed to just the general tags applied via `var.volume_tags`.
This does not break backwards compatibility - it is purely additive with no additional variables.
- [ X] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ X] I have tested and validated these changes using one or more of the provided `examples/*` projects
- [X ] I have executed `pre-commit run -a` on my pull request
Used the docker version and all tests passed except the `Terraform wrapper with for_each in module`. The linter changed the URL in the source lines, replacing every occurrence of `ec2-instance` with `lint`, so I did not commit …
=> feat: Add unique tags to EBS block devices

README.md, examples/complete/README.md, examples/complete/main.tf, examples/complete/versions.tf, main.tf, variables.tf, versions.tf, wrappers/main.tf
I have implemented the fix for the deprecation warning of cpu_core_count and cpu_threads_per_core attributes. Those can now be specified using the cpu_options block.
In addition, this PR adds the support for AMD SEV-SNP which is also a new attribute that can be set via the cpu_options block.
- Resolves #332 
- Resolves #333 
Yes, customers can no longer use the  cpu_core_count and cpu_threads_per_core variables anymore.
Those have been removed in favor of a new variable cpu_options that can be used as below:
```
cpu_options = {
core_count       = 2
threads_per_core = 1
}
```
=> feat: Implementation of the cpu_options block and addition of support for AMD SEV-SNP

.pre-commit-config.yaml, examples/complete/README.md, examples/complete/main.tf, examples/complete/outputs.tf
Added an example as an attempt to reproduce #338, but I can't reproduce it.
=> chore: Added example with ignore_ami_changes

main.tf
#350  Description: 
Create an ec2 instance without ssm permission with cause error.
This account or role can still create an instance in console.
The root cause is because this line of code in main.tf in line 9:
```
data "aws_ssm_parameter" "this" {
count = local.create ? 1 : 0
name = var.ami_ssm_parameter
}
```
Request to make the call data aws_ssm_parameter optional, something like when ami is specified, then no need to call ssm parameter to get the ami id: 
```
#main.tf
ami                  = try(coalesce(var.ami, nonsensitive(data.aws_ssm_parameter.this[0].value)), null)
```
Because it coalesce the `var.ami` and the `nonsensitive(data.aws_ssm_parameter.this[0].value))`, so we only need it when `var.ami` is not specified. So it should be check for null when use data to call to ssm.
``` …
```
=> feat: Remove call data ssm parameter when ami id is specified

README.md, examples/complete/README.md, examples/complete/outputs.tf, examples/volume-attachment/README.md, examples/volume-attachment/main.tf, examples/volume-attachment/outputs.tf, outputs.tf
Added `availability_zone` output. The `availability_zone` of the created instance is useful information to use outside of the module. 
When creating multiple EC2 instances in multiple AZs, in most cases, we would like to have the EBS volume in the same AZ as the created EC2. As a trick we can use `data.aws_instance` with loop or a map of AZs and `random_suffle`,
but it does not look nice. In my opinion having `availability_zone` output would get out of tricks and make the code cleaner and easier to read.
This PR resolves #341 and #264
None
Deployed `volume-attachment` example:
```hcl
terraform plan --target module.ec2 --target aws_volume_attachment.this --target aws_ebs_volume.this
+ resource "aws_ebs_volume" "this" {
+ arn               = (known after apply)
+ availability_zone = …
```
=> feat: Add `availability_zone` output

.github/workflows/pr-title.yml, .github/workflows/pre-commit.yml, .pre-commit-config.yaml, README.md, examples/complete/README.md, examples/session-manager/README.md, examples/volume-attachment/README.md, wrappers/versions.tf
- Update CI workflow versions to latest
- Updates our workflows to use the latest versions
- Removes warnings for Python 3.12 in runners
- No
=> fix: Update CI workflow versions to latest

README.md, examples/complete/README.md, examples/complete/versions.tf, examples/session-manager/README.md, examples/session-manager/versions.tf, versions.tf, wrappers/versions.tf
Lower the Terraform version to 1.5.7 to avoid forcing anyone to reread the HashiCorp license agreement, only to find out they can still use a recent version of Terraform.
=> fix: Lower minimum Terraform version to 1.5.7

README.md, main.tf
- Set Name tag to var.name if it is not "", otherwise use tags
- Minor change to README file, encourage users to use t3 instead of super old t2 instance type.
- Resolves #442 
No breaking changes.
=> fix: Avoid setting `Name` tag when a value has not been provided for `name`
